=== BeeeOn/common/specifications/types.dtd
<!ELEMENT types (type*)>
<!ELEMENT type (name, var, unit?, transform?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT var (#PCDATA)>
<!ELEMENT unit (#PCDATA)>
<!ELEMENT transform (from, to)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>

<!ATTLIST types
        version         CDATA   #REQUIRED
        >
<!ATTLIST type
        id              CDATA   #REQUIRED
        >
<!ATTLIST var
        size            CDATA   #REQUIRED
        >

<!-- Variables entities -->
<!ENTITY int "int">
<!ENTITY float "float">
<!ENTITY bitarray "bitarray">

<!-- Units entities -->
<!ENTITY celsius "&#176;C">
<!ENTITY percent "&#37;">
<!ENTITY hpascal "hPa">
<!ENTITY lux "lx">
<!ENTITY decibel "dB">
<!ENTITY ppm "ppm">
<!ENTITY seconds "s">

=== BeeeOn/common/specifications/types.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE types SYSTEM "types.dtd">
<types version="1">
	<type id="0x01">
		<name>T:ENUM</name>
		<var size="1">int</var>
	</type>
	<type id="0x02">
		<name>T:HUMIDITY</name>
		<var size="1">int</var>
		<unit>&percent;</unit>
	</type>
	<type id="0x03">
		<name>T:PRESSURE</name>
		<var size="1">int</var>
		<unit>&hpascal;</unit>
	</type>
	<type id="0x04">
		<name>T:LIGHT</name>
		<var size="4">float</var>
		<unit>&lux;</unit>
		<transform>
			<from>/100</from>
			<to>*100</to>
		</transform>
	</type>
	<type id="0x05">
		<name>T:NOISE</name>
		<var size="4">float</var>
		<unit>&decibel;</unit>
		<transform>
			<from>/100</from>
			<to>*100</to>
		</transform>
	</type>
	<type id="0x06">
		<name>T:CO2</name>
		<var size="1">int</var>
		<unit>&ppm;</unit>
	</type>
	<type id="0x07">
		<name>T:TEMPERATURE</name>
		<var size="4">float</var>
		<unit>&celsius;</unit>
		<transform>
			<from>/100</from>
			<to>*100</to>
		</transform>
	</type>
</types>
